dist: trusty
language: java # Define the language
jdk: # Define the execution environments
- openjdk8
- oraclejdk8

script: # Build the project
- mvn clean package jacoco:report cobertura:cobertura

after_success: # Notify users about the result
- bash <(curl -s https://codecov.io/bash) -t ea78d9c3-2d0a-4ae4-b311-5996940c9614
